name: "CD Pipeline"
on:
  workflow_run: 
    workflows: ["React-CI-CD pipeline/workflow"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v4

      - name: "Setup Node Js"
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: "Setup Vercel CLI"
        run: npm install -g vercel

      - name: "Download Build files"
        uses: actions/download-artifact@v4
        with:
          name: build
          path: React-ci-cd/dist
          run-id: ${{ github.event.workflow_run.id }}
          github_token: ${{ github.token }}

      - name: "Debug - List files"
        run: ls -R

      - name: "Deploy to Vercel"
        run: vercel ./dist --prod --token=${{ secrets.VERCEL_TOKEN }} --confirm
