name: "React-CI-CD pipeline/workflow" # name of the pipeline
on: #events from on to line 6, when we push the event is triggered
    push:
        branches:
            - master
            - main
jobs:
    build-and-test: # job name
        runs-on: ubuntu-latest # runner machine
        steps:
            - name: "Setup Node Js"
              uses: "actions/setup-node@v4" # helps in defining github actions
              with: # input to predefined actions of github
                node-version: "21"
            - name: "Check node version"
              run: node --version # linux command with run
            - name: "Clone the repo"
              uses: "actions/checkout@v2"
            - name: "Install dependencies"
              run: "npm install"
              working-directory: React-ci-cd
            - name: "List directories"
              run: ls -la
              working-directory: React-ci-cd
            - name: "Run Build"
              run: num run build
              working-directory: React-ci-cd

            - name: "Upload product-ready build files"
              uses: actions/upload-artifacts@v4
              with:
                name: build
                path: dist
                working-directory: React-ci-cd

